#!/bin/bash

PROFILE="mixbook-development-mfa"
GEM_NAME=$(ls *.gemspec | cut -d . -f 1)
REPOSITORY="s3://mixbook-gems/$GEM_NAME"

echo ">> Repository: $REPOSITORY"

while getopts ":p:g:" opt; do
  case $opt in
    p)
      PROFILE=${OPTARG}
      ;;
    g)
      GEM_NAME=${OPTARG}
      ;;
  esac
done

echo $GEM_NAME

echo ">> Download Remote"
aws s3 sync $REPOSITORY pkg/. --profile $PROFILE --region us-east-1

echo ">> Build Gem"
rake build

gem generate_index -v --directory pkg

echo ">> Release"
aws s3 sync pkg/. $REPOSITORY --profile $PROFILE --region us-east-1
